name: Run Infra Guard tool
on:
    push:
        branches: 
            - 'main'
    workflow_dispatch:

jobs:
    run-infra-gaurd-tool:
        name: Update terraform variables
        uses: ./.github/workflows/build-and-run-tool.yaml
        secrets:
            AWS_DEFAULT_REGION: ${{ secrets.AWS_DEFAULT_REGION }}
            AWS_ACCOUNT_ID: ${{ secrets.AWS_ACCOUNT_ID }}
            AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
            AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
            AWS_SESSION_TOKEN: ${{ secrets.AWS_SESSION_TOKEN }}
